/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.app.juegomuseos.views;

import com.gf.app.juegomuseos.utils.GameConstants;
import com.gf.app.juegomuseos.utils.GameData;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * GUIPrincipal: vista del controlador {@link MainController} donde se muestra
 * un menu principal.
 *
 * @see MainController
 *
 * @author priparno
 * @author fercaslu
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * panelLogo: un panel con el logo.
     */
    private JPanel logoPanel;
    /**
     * optionsPanel: un panel con las opciones.
     */
    private JPanel optionsPanel;

    /**
     * labelLogo: una etiqueta con el logo.
     */
    private JLabel labelLogo;
    /**
     * options: una lista de botones con las opciones.
     */
    private List<JButton> options = new ArrayList<>();

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        try {
            UIManager.setLookAndFeel(GameData.STYLE);
            this.setUndecorated(true);
            initComponents();
            setFrame();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(GUIMuseumsTF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * setFrame: es el metodo principal que coloca en la vista el logo y las
     * opciones.
     */
    private void setFrame() {
        this.setExtendedState(MAXIMIZED_BOTH);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.getContentPane().setSize(screenSize);
        this.getContentPane().setLayout(new BorderLayout());
        setLogo();
        setButtons();
    }

    /**
     * setLogo: coloca el logo en la ventana.
     */
    private void setLogo() {
        logoPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        labelLogo = new JLabel("HEY");
        logoPanel.add(labelLogo);
        this.getContentPane().add(logoPanel, BorderLayout.NORTH);
    }

    /**
     * setButtons: coloca y crea los botones de las opciones.
     */
    private void setButtons() {
        optionsPanel = new JPanel(new FlowLayout());
        optionsPanel.setSize((int) (this.getContentPane().getWidth() * 0.7), (int) (this.getContentPane().getHeight() * 0.3));
        JPanel gridPanel = new JPanel(new GridLayout(GameConstants.MAIN_MENU_OPTIONS.length, 0));
        for (String MAIN_MENU_OPTIONS : GameConstants.MAIN_MENU_OPTIONS) {
            JButton but = new JButton(MAIN_MENU_OPTIONS);
            but.setPreferredSize(new Dimension(optionsPanel.getWidth(), optionsPanel.getHeight() / GameConstants.MAIN_MENU_OPTIONS.length));
            options.add(but);
            gridPanel.add(but);
        }
        optionsPanel.add(gridPanel);
        this.getContentPane().add(optionsPanel, BorderLayout.CENTER);
    }

    //GETTER/SETTER
    /**
     * getLabelLogo: devuelve un {@link JLabel} que contendra la imagen.
     *
     * @return un {@link JLabel}
     */
    public JLabel getLabelLogo() {
        return labelLogo;
    }

    /**
     * getOptions: devuelve una lista de {@link JButton} que contiene las
     * opciones.
     *
     * @return una lista de {@link JButton}
     */
    public List<JButton> getOptions() {
        return options;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
