/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gf.app.juegomuseos.views;

import com.gf.app.juegomuseos.utils.GameConstants;
import com.gf.app.juegomuseos.utils.GameData;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.SwingConstants;

/**
 * GUISettings:
 *
 * @author priparno
 */
public class GUISettings extends javax.swing.JDialog {

    private JPanel panelOptions;

    private JButton styleButton;

    private JSlider volumeSlider;

    /**
     * Creates new form GUISettings
     *
     * @param parent
     * @param modal
     */
    public GUISettings(GUIPrincipal parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setFrame();
    }

    private void setFrame() {
        this.setResizable(false);
        this.getContentPane().setLayout(new BorderLayout());
        panelOptions = new JPanel(new GridLayout(4, 0));
        //ajustes de estilo
        setStylePanel();
        //ajustes de sonido
        setVolumePanel();
        this.getContentPane().add(panelOptions);
        this.setPreferredSize(new Dimension((int) (GameConstants.SCREEN_SIZE.width * 0.3), (int) (GameConstants.SCREEN_SIZE.height * 0.5)));
        this.pack();
        this.setLocationRelativeTo(null);
    }

    private void setStylePanel() {
        styleButton = new JButton(GameData.getInfoStyle()[0]);
        JLabel styleLabel = new JLabel("AJUSTES DE ESTILO");
        styleLabel.setFont(this.getFont().deriveFont(Font.BOLD, 22f));
        styleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        panelOptions.add(styleLabel);
        panelOptions.add(styleButton);
    }

    private void setVolumePanel() {
        volumeSlider = new JSlider(-80, 6, (int) Float.parseFloat(GameData.getInfoVolume()[1]));
        volumeSlider.setPaintTrack(true);
        JLabel volumeLabel = new JLabel("AJUSTES DE SONIDO");
        volumeLabel.setFont(this.getFont().deriveFont(Font.BOLD, 22f));
        volumeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        panelOptions.add(volumeLabel);
        panelOptions.add(volumeSlider);
    }

    public JSlider getVolumeSlider() {
        return volumeSlider;
    }
    
    public JButton getStyleButton() {
        return styleButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
