/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gf.app.juegomuseos.views;

import com.gf.app.juegomuseos.utils.Colors;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author priparno
 */
public class ResultDialog extends javax.swing.JDialog {

    private JLabel msgText;
    private JFrame parent;
    private Dimension windowSize;

    /**
     * Creates new form ResultDialog
     * 
     * @param parent
     * @param correct
     */
    public ResultDialog(JFrame parent, boolean correct) {
        this.setUndecorated(true);
        this.setModal(true);
        this.parent = parent;
        initComponents();
        msgText = new JLabel();
        setFrame();
        setLabelStyle();
        if (correct) {
            setCorrect();
        } else {
            setIncorrect();
        }
    }

    private void setFrame() {
        this.setResizable(false);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        windowSize = new Dimension((int) (screenSize.width * 0.5), (int) (screenSize.height * 0.3));
        this.setSize(windowSize);
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(msgText, BorderLayout.CENTER);
        msgText.setHorizontalAlignment(SwingConstants.CENTER);
        this.setLocationRelativeTo(null);
    }

    private void setCorrect() {
        msgText.setText("Correcto");
        this.getContentPane().setBackground(Colors.GREEN);
    }

    private void setIncorrect() {
        msgText.setText("Incorrecto");
        this.getContentPane().setBackground(Colors.RED);
    }

    private void setLabelStyle() {
        Font parentFont = parent.getFont();
        msgText.setFont(parentFont.deriveFont(Font.BOLD, 50f));
    }

    public void initTimer() {
        JDialog pane = this;
        Thread t = new Thread(() -> {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                System.out.println("Error");
            }
            pane.dispose();
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
